import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "FirstWatch POC",
  description: "Generated by Brian McCurdy",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
};

export default Layout;
